# Generated by Django 4.2.20 on 2025-03-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
